### ISSUE TITLE
Ignore bak file in git. 

### ISSUE THREAD

**Issue by yubarajkalathoki** [yubarajkalathoki/aadim-innovation-jan-27-2022#1]
*.bak file should not be added in git. Please fix this issue.

**Comment by yubarajkalathoki** [comment]
Yo issue ta ajhai samma kasaile pani solve gareko chhaina ta sathi ho.

**Comment by SajanKc** [comment]
I have fixed this in: 397b238614f66daaa06833ceec00477d8fc9d04f
